### ISSUE TITLE
Finalizar entrada de dados.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#15]
Definir a função para o banco de dados.

**Comment by drbeco** [comment]
:question: 

"Banco de dados" é um termo técnico que envolve os grandes gerenciadores de dados, como MySQL, Oracle, etc. Não vejo necessidade de um banco de dados aqui. Sobre o que seria?

**Comment by JoaoPaacheco** [comment]
Banco de dados eu falo no sentido de passar as informações do arquivo texto para as listas, não encontrei um termo melhor para isso. O senhor aconselharia algum?

**Comment by drbeco** [comment]
Renomeie este issue para "Finalizar entrada de dados"

**Comment by JoaoPaacheco** [comment]
Tudo pronto e funcionando.
