### ISSUE TITLE
Comentar programa.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#16]
Comentar todo o programa para melhor entendimento.

**Comment by drbeco** [comment]
Comentários doxygen

**Comment by pvpatriota** [comment]
Ok professor.

**Comment by pvpatriota** [comment]
Assim como a issue relacionada com a revisão dos comentários, esta passará para a próxima milestone, já que os comentários serão feitos com o doxygen.

**Comment by JoaoPaacheco** [comment]
Entrada de dados e threads com comentários.
