### ISSUE TITLE
Criar esqueleto base do arquivo ex12.c

### ISSUE THREAD

**Issue by pvpatriota** [pvpatriota/discreta12bolinhas#2]
Criar o esqueleto base para o programa da rede de petri melhorada.

**Comment by JoaoPaacheco** [comment]
Criado esqueleto com funções básicas que serão utilizadas no curso do programa.

**Comment by drbeco** [comment]
Este talvez tenha sido precipitado. As funções não parecem que vão dar conta da análise de sistema feita tão por cima.

Mas tudo bem para ser esqueleto. Quando precisarem alterar a estrutura, criem novos bugs e deixe esse fechado.
