### ISSUE TITLE
Testar funcionamento.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#23]
Testar funcionamento do programa como preparação para merge com master.

**Comment by drbeco** [comment]
"Testar " o programa é ato contínuo a cada commit, push, debug, compilação, etc.
Não dá para criar um issue com data nisso. Se fez push é porque testou. Não vai mandar pro master algo com bug. E pro develop pode até acontecer de ter um bug, mas é obvio que foi pelo menos testado antes do push.

**Comment by JoaoPaacheco** [comment]
Entendido.
