### ISSUE TITLE
Revisar programa - comentários.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#24]
Revisar programa em busca de possíveis comentários que não tenham sido feitos como preparação para merge com master.

**Comment by pvpatriota** [comment]
Todos os comentários serão feitos pelo doxygen e por isso esse issue será passado para a próxima Milestone

**Comment by pvpatriota** [comment]
Este issue será finalizado juntamento com o Issue dos comentários, pois ambos serão feitos e conferidos pelo doxygen

**Comment by JoaoPaacheco** [comment]
Fechando issue por estar duplicado.
