### ISSUE TITLE
Estudar allegro.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#26]
Estudar como realizar projetos utilizando allegro.

**Comment by drbeco** [comment]
Para ajudar: implemente o pequeno exemplo que deixei na pasta de discreta no dropbox.

**Comment by pvpatriota** [comment]
Ok professor, vou implementar e estudar o exercício.

**Comment by pvpatriota** [comment]
Professor, como eu posso usar o comando make para fazer as compilações das funções do alegro? Tem como eu editar o arquivo para incrementar os comandos para compilar com a biblioteca alegro que o senhor disponibilizou no exercício exemplo?

**Comment by pvpatriota** [comment]
Arquivo makefile já foi configurado e está executando as compilações perfeitamente.

**Comment by JoaoPaacheco** [comment]
Era necessário alguma mudança para o allegro?

**Comment by pvpatriota** [comment]
Sim Jope10, o arquivo makefile se encontrava sem os seguintes flags para a compilação `allegro-config --cflags --libs`. 
Por isso não estava sendo possível fazer a compilação do código após inserir o esqueleto do allegro no mesmo, então entrei no arquivo makefile e fiz as devidas alterações.
Resultado disso, o programa está compilando o código normalmente e sem erros.

**Comment by JoaoPaacheco** [comment]
Massa.

**Comment by pvpatriota** [comment]
Os estudos para o alegro foram concluídos. A partir de agora serão inseridos os códigos no programa.
