### ISSUE TITLE
Fluxograma allegro.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#27]
Definir a ordem de funcionamento do allegro.

**Comment by pvpatriota** [comment]
A ordem de funcionamento será a seguinte:

Primeiramente será chamada a função gerar imagem, dentro desta função serão chamadas as respectivas sub funções, com a finalidade de desenhar os estados, as transições e os arcos e relacionar todos eles de acordo com os arquivos de entrada disponibilizados: entrada-petri-1/2/3.txt

**Comment by pvpatriota** [comment]
Fluxograma definido e código implementado e funcionando como o esperado. Com isso, este issue se dá por concluído e será finalizado.
