### ISSUE TITLE
Definir o esqueleto das funções do allegro.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#28]
Definir o esqueleto das funções do allegro.

**Comment by pvpatriota** [comment]
As funções para o esqueleto do alegro foram definidas e são as seguintes:

gerar imagem
desenha estados
desenha transições
desenha arcos

**Comment by pvpatriota** [comment]
A função arctan também foi inserida, pois ela ira calcular a posição dos arcos que entram e que saem.

**Comment by pvpatriota** [comment]
Para finalizar, o esqueleto das funções do alegro já foram implementadas e se encontram funcionando perfeitamente e as imagens estão sendo geradas como o esperado, sendo assim, dou por concluído esse issue e o mesmo será encerrado.
