### ISSUE TITLE
Implementar funções allegro.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#29]
Retirar todos os bugs das funções do allegro.

**Comment by pvpatriota** [comment]
Esqueleto base para o funcionamento do allegro adicionado. Ao decorrer do dia, será implementado as funções básicas para testes.

**Comment by pvpatriota** [comment]
Todos os bugs relacionados ao alegro já foram retirados.

**Comment by pvpatriota** [comment]
As funções do alegro foram todas implementadas e todas estão funcionando sem bugs. Os arquivos gerados a partir de cada entrada já se encontram dentro do repositório do git.
Com tudo funcionando, este issue será encerrado
