### ISSUE TITLE
Adicionar arquivos ao repositório

### ISSUE THREAD

**Issue by pvpatriota** [pvpatriota/discreta12bolinhas#3]
Adicionar os arquivos LICENSE, README e makefile ao repositório do exercício 12.

**Comment by pvpatriota** [comment]
PS.: Adicionar o arquivo AUTHORS

**Comment by pvpatriota** [comment]
Adicionado arquivos solicitados ao repositório.

**Comment by drbeco** [comment]
Não fechar este bug até adicionar todos arquivos. É o esqueleto completo.
Inclui código C, arquivos de entrada, e demais que forem necessários

**Comment by pvpatriota** [comment]
Ok professor! Permanecerá aberto até que o programa esteja concluído.
Aproveito aqui e pergunto:  há a possibilidade de vincular mais de uma milestone a um mesmo issue?

**Comment by drbeco** [comment]
"programa concluído"?

Acho que não. Só até adicionar os arquivos necessários e com isso concluir a fase inicial do esqueleto.

Esse issue é para ser vinculado ao primeiro milestone, terminando hoje. E fechando hoje.

Milestones tem data para terminar, portatno não é possível associar a dois. Seria dizer que uma tarefa tem duas datas para terminar, o que não faz sentido.

**Comment by drbeco** [comment]
Estão faltando apenas os arquivos txt de entrada:

http://tinyurl.com/hydrabox

**Comment by Jope10** [comment]
Irei adicionar hoje mesmo.

**Comment by JoaoPaacheco** [comment]
Arquivos de entrada adicionados, professor. Realmente tinha esquecido dos arquivos de entrada.
