### ISSUE TITLE
Buscar otimização - entrada.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#34]
Buscar possíveis pontos de otimização na entrada de dados.

**Comment by drbeco** [comment]
Ok, parece duplicado. A entrada de dados, marque-a para ficar pronta e otimizada no máximo até v1.0

Confira se não é bug duplicado e feche um dos dois com o mesmo assunto.

**Comment by JoaoPaacheco** [comment]
Duplicado.
