### ISSUE TITLE
Buscar otimização - entrada de dados.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#35]
Buscar possíveis otimizações no banco de dados.

**Comment by drbeco** [comment]
Entrada de dados. Isso não deve estar para versão 2.0. A entrada de dados é uma das primeiras fases da programação. Acerte-a e otimize-a no máximo até v1.0.

**Comment by drbeco** [comment]
Renomear - retire a palavra "banco" ou "banco de dados" de todos issues correspondentes. Utilize "entrada de dados"

**Comment by JoaoPaacheco** [comment]
Feito.
