### ISSUE TITLE
Buscar otimizações - allegro.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#37]
Buscar possíveis otimizações no allegro.

**Comment by pvpatriota** [comment]
Verificar o código do allegro para tentar corrigir os triangulos que são utilizados como setas nos arcos.

**Comment by pvpatriota** [comment]
Os triangulos que estavam com erro de posicionamento foram corrigidos, assim como os seus respectivos formatos. Agora todos demonstram ser realmente triangulos. Com isso, dou por encerrado esse issue.
