### ISSUE TITLE
Testar programa.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#39]
Testar programa.

**Comment by drbeco** [comment]
Testar programa é algo que não se faz com "data marcada", portanto não funciona para ficar como bug.

É uma atividade paralela, que faz parte da programação. Cada função nova, cada compilação, você testa. Você faz debug. Você corrije erros. Reescreve e recompila antes de fazer o push.

Este bug é inválido.

**Comment by JoaoPaacheco** [comment]
Fechando issue.
