### ISSUE TITLE
Adicionar Colaboradores ao repositório

### ISSUE THREAD

**Issue by pvpatriota** [pvpatriota/discreta12bolinhas#4]
Adicionar ao repositório como colaboradores o aluno João Pedro, cujo nome de usuário do git é Jope10 e adicionar o professor Ruben Carlo, cujo nome de usuário do github é Dr.Beco.

**Comment by pvpatriota** [comment]
Os colaboradores citados acima já foram adicionados ao repositório.

**Comment by drbeco** [comment]
Este talvez tenha sido precipitado. As funções não parecem que vão dar conta da análise de sistema feita tão por cima.

Mas tudo bem para ser esqueleto. Quando precisarem alterar a estrutura, criem novos bugs e deixe esse fechado.
