### ISSUE TITLE
Função enviar tokens.

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#41]
Definir função que irá enviar tokens de um estado para outro mediante ordem da transição.

**Comment by JoaoPaacheco** [comment]
Transferido para milestone em que o programa irá simular a rede.

**Comment by pvpatriota** [comment]
Transferida Milestone para a versão 1.0, onde o programa irá funcionar sem o alegro estar 100% implementado

**Comment by JoaoPaacheco** [comment]
Definida.
