### ISSUE TITLE
Criar pelo menos 5 issues sobre cada fase

### ISSUE THREAD

**Issue by drbeco** [pvpatriota/discreta12bolinhas#5]
Conforme comentado em sala:
- Criar pelo menos 5 issues sobre cada milestone, total 30. (até hoje, v0.1, e fechar este issue)
- E lembrar da meta de **pelo menos** 50. Porém, claro, colocar mais na medida do necessário.

**Comment by JoaoPaacheco** [comment]
Issues criadas e fechadas. Versão 0.1 liberada.
Vou trabalhar nos issues das outras versões.

**Comment by drbeco** [comment]
Issues criadas?

Não tem nenhuma issue nova na lista. Estou vendo apenas 8 fechadas.

**Comment by drbeco** [comment]
7 fechadas e essa reaberta

**Comment by drbeco** [comment]
ok

**Comment by JoaoPaacheco** [comment]
Liberando v0.1
