### ISSUE TITLE
DOXYGEN

### ISSUE THREAD

**Issue by JoaoPaacheco** [pvpatriota/discreta12bolinhas#56]
Liberar DOXYGEN.

**Comment by pvpatriota** [comment]
Documentação com o doxygen já foi iniciada e será finalizada não mais tarde até a noite de hoje.

**Comment by pvpatriota** [comment]
O Doxygen foi concluido, porém quando é dado o comando para gerar a documentação, ele relata vários warnings, dizendo que as variaveis não foram comentadas, apesar de terem sido e de ter sido criado o arquivo html e dentro dele estar especificando tudo corretamente.

**Comment by pvpatriota** [comment]
Professor, o senhor poderia mostrar um exemplo de como devo preencher o arquivo groups.dox?
Obrigado
